language:
  - python

services:
  - docker

before_install:
  - docker build -f ./dockerfile_gruserver -t dangawne/energy_gru .

deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"
  - docker image push dangawne/energy_gru
