language:
  - python

services:
  - docker

before_install:
  - docker build -f ./dockerfile_gruserver -t dangawne/energy_gru .

before_deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"

deploy:
  provider: script
  script: docker image push dangawne/energy_gru
  on:
    branch: main
