channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.7.9
- pytorch=1.7.1
- torchvision=0.8.2
- ignite=0.4.1
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
name: mlflow-env
